name: GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - docs/**
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python3 -m pip install mkdocs==1.6.1
          python3 -m pip install mkdocs-material==9.6.5
          python3 -m pip install mkdocs-include-markdown-plugin==7.1.4
          python3 -m pip install mkdocs-macros-plugin==1.3.7
          python3 -m pip install mkdocs-with-pdf==0.9.3
          python3 -m pip install mkdocs-print-site-plugin==2.6.0

      - name: Build mkdocs
        run: |
          mkdocs build -f ./docs/mkdocs.en.yml
          cp -av ./docs/index.html ./docs/site

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.ACTION_TOKEN }}
          publish_dir: ./docs/site
          publish_branch: gh-pages
