name: Release Package

on:
  push:
    tags:
      - 'emd-*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3

    - name: Build wheel
      run: poetry build -f wheel

    - name: Get tag name
      id: get_tag
      run: echo "TAG_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV

    - name: Rename wheel
      run: |
        WHEEL_FILE=$(ls dist/*.whl)
        mv "$WHEEL_FILE" "dist/${{ env.TAG_NAME }}.whl"

    - name: Install GitHub CLI
      run: sudo apt-get install -y gh

    - name: Create GitHub Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release create ${{ env.TAG_NAME }} dist/${{ env.TAG_NAME }}.whl --title "Release ${{ env.TAG_NAME }}" --notes "Automated release of ${{ env.TAG_NAME }}"